const cards = [
  ["1", "prizes/1.png"],
  ["2", "prizes/2.png"],
  ["3", "prizes/3.png"],
  ["4", "prizes/4.png"],
  ["5", "prizes/5.png"],
  ["6", "prizes/6.png"],
  ["7", "prizes/7.png"],
  ["8", "prizes/8.png"],
  ["9", "prizes/1.png"],
  ["10", "prizes/2.png"],
  ["11", "prizes/3.png"],
  ["12", "prizes/4.png"],
  ["13", "prizes/5.png"],
  ["14", "prizes/6.png"],
  ["15", "prizes/7.png"],
  ["16", "prizes/8.png"],
];
const urls = [
  "prizes/1.png",
  "prizes/2.png",
  "prizes/3.png",
  "prizes/4.png",
  "prizes/5.png",
  "prizes/6.png",
  "prizes/7.png",
  "prizes/8.png",
  "prizes/1.png",
  "prizes/2.png",
  "prizes/3.png",
  "prizes/4.png",
  "prizes/5.png",
  "prizes/6.png",
  "prizes/7.png",
  "prizes/8.png",
];
export { cards, urls };
